### ISSUE TITLE
Cannot load .XLL add-in

### ISSUE THREAD

**Issue by S1nus** [MarcusRainbow/xladd-util#4]
Hi @MarcusRainbow !

Love the idea of making .XLL add-ins in Rust. I cloned this as well as xladd and ran "cargo run" inside it on Windows. It output a bunch of files, including xladd_util.dll, which I renamed to xladd_util.xll. 

I attempted to load this add-in into Excel and it worked, but the functions don't appear to be working. Any idea what I'm doing wrong? I'd like to contribute to this project as I am a .XLL developer seeking the functionality of Rust.

**Comment by S1nus** [comment]
May be because VBA wrappers around DLL functions are needed in Excel. I'll try that when I get around to it.

**Comment by MarcusRainbow** [comment]
Hi S1nus,
Excel does not need VBA to run functions in a addin. In fact, it does not
even need the addin to be called .xll rather than .dll. I am afraid I only
have a 64bit Windows 10 machine with 64bit Excel 2016, but for me, I can
just load the xladd_util.dll into Excel by using the File/Open menu, and
the functions I have registered become available to call in cells. For
example, I can put =xuVersion into a cell and I get the version string.

Are you using 64bit everything? This ought to work with 32bit, but I do not
have the means to test it.

Normally, if you load a dll that does not support the xll functions
properly, Excel thinks you are just trying to load some random dll, and it
opens it as if it were a text document -- you get a load of garbage in a
spreadsheet --, so it is a good sign if that is not happening to you.

There are two possible ways to debug, that I have discovered. First is to
use OutputDebugStringA to write trace. You can pick this up using the
application DebugView (free download from Microsoft). The other possibility
is to use VisualStudioCode as a debugger. If you code a DebugBreak into
xlAutoOpen and start Excel by specifying it in the launch.json file, you'll
find it catches the breakpoint and you can debug through it.

Another question, are you using the Windows toolchain, rather than the LLVM
one?
Marcus

**Comment by S1nus** [comment]
Hi Marcus,

Just realized I am using 32 bit. I'll download 64 and try again.

**Comment by S1nus** [comment]
Update, everything works as expected when I use the 64 bit version of Excel. Strange because it you only use 32 bit ints in the code. I wonder if to support 32 bit Excel you would need to reduce them all to 16 bit values?

Thanks for your help. Let me know if there's any way I can help! In the mean time I'm going to start making an add-in with this, I have an add-in which allows you to make HTTP requests from Excel cells and return the result as array functions which get automatically resized asynchronously, and I'd like to move it from C#.NET to Rust as I think it will be less buggy and perform better.

**Comment by MarcusRainbow** [comment]
Awesome that you got it working. Thanks for letting me know.

One advantage of the xll interface compared with C# is that you can do
things asynchronously, though it's not something I've tried. Certainly
worth trying for your html application.

64bit Windows uses the LLP64 convention for integer sizing -- see
https://en.wikipedia.org/wiki/64-bit_computing. Not many operating systems
use 64bit for standard integers.

My next task for this addin is writing some Rust macro code, so you can
automatically convert a function that works with standard Rust types, &str
and &[f64] for example, wrapping it in a thunk that has XLOPER12 arguments.
This seems pretty complicated.

Certainly it would be very useful to test out some examples that are rather
less trivial than the ones in xladd-util. Sounds as if that is what you are
doing anyway. Please let me know about any problems you run into.

I found one weird one, which is documented by Microsoft. The help text for
functions and arguments is often truncated by a few characters -- they
recommend sticking a few spaces on the end.

Marcus
